kibana:
    image: kibana
    ports:
        - "5601:5601"
    links:
        - elasticsearch
elasticsearch:
    image: elasticsearch
    volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
logstash:
    image: logstash
    links:
        - elasticsearch
    volumes:
        - ./logstash/conf.d:/etc/logstash/conf.d
        - ./logstash/docker-entrypoint.sh:/docker-entrypoint.sh

# https://www.digitalocean.com/community/tutorials/how-to-install-elasticsearch-logstash-and-kibana-elk-stack-on-ubuntu-14-04
# logstash -f /etc/logstash/conf.d/*
# $ docker run --name some-kibana --link some-elasticsearch:elasticsearch -p 5601:5601 -d kibana
# $ docker run -it --rm -v "$PWD/logstash/conf.d":/config-dir logstash logstash -f /config-dir/logstash.conf